apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/config: {{ .Values.html | toYaml | sha256sum }}
    spec:
      containers:
        - name: nginx
          image: nginx:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: index-html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: index-html-volume
          configMap:
            name: {{ .Values.name }}-index-html
