repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

# i don't know what the heck this black magic is, but for some reason without this
# `helmfile apply` fails on the `helm diff` step when validting that the alloy crd
# is present
apiVersions:
  - collectors.grafana.com/v1alpha1/Alloy

releases:
  - name: loki
    chart: grafana/loki
    version: 6.44.0
    namespace: monitoring
    values:
      - ./loki/values.yaml

  # To get the 'admin' password, run: $ kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
  - name: grafana
    chart: grafana/grafana
    version: 10.3.0
    namespace: monitoring
    values:
      - ./grafana/values.yaml

  - name: k8s-monitoring
    chart: grafana/k8s-monitoring
    version: 3.6.2
    namespace: monitoring
    values:
      - ./k8s-monitoring/values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "--server-side"
          - "-f"
          - "https://github.com/grafana/alloy-operator/releases/download/alloy-operator-0.3.14/collectors.grafana.com_alloy.yaml"
