grafana.ini:
  server:
    domain: grafana.monitoring.jpgray.ca
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
ingress:
  enabled: true
  hosts:
    - grafana.monitoring.jpgray.ca
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: traefik
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.monitoring.jpgray.ca
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        isDefault: true
        url: http://loki-gateway.monitoring.svc.cluster.local/
persistence:
  enabled: true